const spacing = {
   'utilsSpace3Xl': '4.5rem',
   'utilsSpace2Xl': '3rem',
   'utilsSpaceXl': '2.5rem',
   'utilsSpaceL': '2rem',
   'utilsSpaceM': '1.5rem',
   'utilsSpaceS': '1rem',
   'utilsSpaceXs': '0.5rem',
   'utilsSpace2Xs': '0.25rem',
   'utilsRadius0': '2rem',
   'utilsRadius1': '2rem',
   'utilsRadius2': '2.0000000000000004rem',
   'utilsRadius3': '2rem',
   'utilsRadius100': '2rem',
   'utilsRadius4': '2rem',
   'utilsShadowRaised': '2rem',
   'utilsShadowFloating': '2rem',
   'utilsShadowOverlay': '2rem',
   'utilsShadowDialog': '2rem',
   'utilsBorderAll': '2rem',
}