# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
        env:
          NPMRC_AUTH: ${{ secrets.NPMRC_AUTH }}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://github.com/sirganya/local-design-token-pkg.git
      - run: git config --global user.email "greg@concretenoise.com"
      - run: git config --global user.name "Greg Kavanagh"
      - run: npm version patch
        env:
          NPMRC_AUTH: ${{ secrets.NPMRC_AUTH }}
      - run: npm publish
        env:
          NPMRC_AUTH: ${{ secrets.NPMRC_AUTH }}
      - run: curl -i -H "Authorization:token {{ secrets.DISPATCH}}" https://api.github.com/repos/sirganya/local-ui/dispatches -d '{"event_type":"release"}'
     